let g:user42 = 'ddi-nico'
let g:mail42 = 'ddi-nico@student.42roma.it'

" No swapfile

set noswapfile

" Attiva la colorazione della sintassi
syntax on

" Mostra i numeri di riga (fondamentale per i bug di Norminette)
set number
" set relativenumber

" Configurazione Tabulazioni standard 42 (1 Tab = 4 Spazi)
set tabstop=4
set shiftwidth=4
set smarttab

" NON usare 'expandtab' (Norminette richiede i TAB reali, non gli spazi!)
set noexpandtab

" Indentazione automatica intelligente
set autoindent
set smartindent

" Evidenzia la colonna 80 (il limite massimo di caratteri per riga di 42)
set colorcolumn=80
highlight ColorColumn ctermbg=darkgray

" Permette l'uso del mouse per scorrere o cliccare
set mouse=a

" Imposta la visualizzazione ad albero
let g:netrw_liststyle = 3

" Synced directory 
let g:netrw_keepdir = 0

" Rimuove il banner informativo in alto per avere più spazio
let g:netrw_banner = 0

" Hide dotfile
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'

" Imposta la larghezza della barra al 25% della finestra
let g:netrw_winsize = 18

" Scorciatoia: premi Ctrl + n per aprire/chiudere la barra laterale
nnoremap <C-n> :Lexplore<CR>

" Main dir
set autochdir

" Copia la selezione visuale nel file temporaneo premendo Ctrl+C 
vmap <C-c> :w! ~/.vim_clip<CR> 

" Incolla il file temporaneo nella posizione del cursore premendo Ctrl+V 
nmap <C-v> :r ~/.vim_clip<CR>
